
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.proyectofechas;

/**
 *
 * @author lucia
 */
public class VerDatos extends javax.swing.JFrame {

    /**
     * Creates new form VerDatos
     */
    public VerDatos() {
        initComponents();
        setTitle("Datos de las personas en el archivo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Nombre: Ana Gómez\nNacimiento:1985-11-05\nMatrimonio:2010-10-30\nLoteria:2020-03-12");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 131, 161, 88));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Nombre: Luis Martínez\nNacimiento:1980-08-15\nGraduacion:2012-12-10\nMatrimonio:2015-04-17\nMuerte:2024-06-06");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 245, 166, 88));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Nombre: Carmen Rodríguez\nNacimiento:1975-07-09\nMatrimonio:2000-05-28\nMuerte:2045-03-22");
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 131, 171, 88));

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Nombre: Laura Sánchez\nNacimiento:1995-09-30\nGraduacion:2018-06-25\nMatrimonio:2022-12-01");
        jScrollPane6.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 245, 171, 88));

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Nombre: Mariana Castro\nNacimiento:1980-06-01\nGraduacion:2002-04-17\nMatrimonio:2005-07-30\nLoteria:2015-11-20");
        jScrollPane8.setViewportView(jTextArea8);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 351, 161, -1));

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("Nombre: Sofía Herrera\nNacimiento:1992-08-11\nGraduacion:2015-12-03\nMatrimonio:2019-04-22\nMuerte:2080-10-12\nLoteria:2023-09-03");
        jScrollPane10.setViewportView(jTextArea10);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 465, 166, -1));

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("Nombre: Esteban Morales\nNacimiento:1978-12-21\nGraduacion:2000-05-10\nMatrimonio:2003-09-14");
        jScrollPane9.setViewportView(jTextArea9);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 351, 165, -1));

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Nombre: Pedro Ramírez\nNacimiento:1965-02-14\nGraduacion:1987-10-08\nMatrimonio:1990-03-25\nMuerte:2000-01-11");
        jScrollPane7.setViewportView(jTextArea7);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 351, 166, -1));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("Nombre: Diego Fernández\nNacimiento:1982-04-17\nGraduacion:2005-07-03\nMatrimonio:2008-11-20\nLoteria:2016-02-18");
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 245, 161, 88));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel1.setText("Personas en el archivo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 36, 439, 50));

        jButton1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        jButton1.setText("Hacer Consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 491, -1, -1));

        jTextArea11.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea11.setRows(5);
        jTextArea11.setText("Nombre: Juan Pérez\nNacimiento:1970-03-15\nGraduacion:1992-06-20\nMatrimonio:1995-09-10\nMuerte:2040-12-01\nLoteria:2010-07-15");
        jScrollPane11.setViewportView(jTextArea11);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 129, 165, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucia\\Downloads\\rosadito.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucia\\Downloads\\rosadito.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 620, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Calculadora ventana = new Calculadora();
        ventana.setVisible(true);
        this.dispose();

    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
